apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream : "true"
  labels:
    app: matches
    stack: echo
    interface: rest
    language: golang
  name: matches
  namespace: bets
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: matches
