apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bets-hpa
  namespace: bets
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bets
  minReplicas: 1
  maxReplicas: 35
  targetCPUUtilizationPercentage: 70
